version: '3.8'

services:
  ads-v14:
    container_name: ads-v14
    network_mode: host
    build:
      context: .
      args:
        - NEXT_PUBLIC_TRACKER_URL=https://track.stakerschoiceads.com
        - NEXT_PUBLIC_APP_URL=https://stakerschoiceads.com
    restart: always
    environment:
      - PORT=3009
      - DATABASE_URL=postgresql://postgres:uzomary_adstracking@127.0.0.1:5432/adstracking
      - DATABASE_SSL=false
      - JWT_SECRET=adtrack_vps_production_secret_2024
      - NEXT_PUBLIC_TRACKER_URL=https://track.stakerschoiceads.com
      - NEXT_PUBLIC_APP_URL=https://stakerschoiceads.com
      - NODE_ENV=production
    volumes:
      - /root/ads-uploads:/app/public/uploads
